/**
 * SCOTT ENGINE - Node.js Implementation
 * Converts images to 3D printable LED sign SCAD files
 * 
 * Uses Moore-Neighbor boundary tracing and Douglas-Peucker simplification
 */

const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

class ScottSignEngine {
  constructor(options = {}) {
    this.tolerance = options.tolerance || 2.0;
    this.lightType = options.lightType || 'silicone_neon_6mm';
  }

  /**
   * Moore-Neighbor Boundary Tracing Algorithm
   * Extracts the outer boundary of a binary shape
   */
  traceBoundary(binaryData, width, height) {
    const getPixel = (x, y) => {
      if (x < 0 || x >= width || y < 0 || y >= height) return 0;
      return binaryData[y * width + x];
    };

    // Find starting point (first white pixel from top-left)
    let startX = -1, startY = -1;
    outer: for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        if (getPixel(x, y) > 0) {
          startX = x;
          startY = y;
          break outer;
        }
      }
    }

    if (startX === -1) return [];

    // Moore neighbor offsets (clockwise from left)
    const neighbors = [
      [-1, 0], [-1, -1], [0, -1], [1, -1],
      [1, 0], [1, 1], [0, 1], [-1, 1]
    ];

    const boundary = [];
    let x = startX, y = startY;
    let dir = 0; // Start direction
    let iterations = 0;
    const maxIterations = width * height * 2;

    do {
      boundary.push([x, y]);
      
      // Search for next boundary pixel
      let found = false;
      for (let i = 0; i < 8; i++) {
        const checkDir = (dir + i) % 8;
        const nx = x + neighbors[checkDir][0];
        const ny = y + neighbors[checkDir][1];
        
        if (getPixel(nx, ny) > 0) {
          x = nx;
          y = ny;
          dir = (checkDir + 5) % 8; // Backtrack direction
          found = true;
          break;
        }
      }

      if (!found) break;
      iterations++;
    } while ((x !== startX || y !== startY) && iterations < maxIterations);

    return boundary;
  }

  /**
   * Douglas-Peucker Line Simplification (Scott-Peucker variant)
   * Reduces points while preserving shape topology
   */
  simplifyPath(points, tolerance) {
    if (points.length < 3) return points;

    const sqDist = (p1, p2) => {
      const dx = p1[0] - p2[0];
      const dy = p1[1] - p2[1];
      return dx * dx + dy * dy;
    };

    const perpendicularDist = (point, lineStart, lineEnd) => {
      const dx = lineEnd[0] - lineStart[0];
      const dy = lineEnd[1] - lineStart[1];
      const d2 = dx * dx + dy * dy;
      
      if (d2 === 0) return Math.sqrt(sqDist(point, lineStart));
      
      const t = Math.max(0, Math.min(1, 
        ((point[0] - lineStart[0]) * dx + (point[1] - lineStart[1]) * dy) / d2
      ));
      
      const projX = lineStart[0] + t * dx;
      const projY = lineStart[1] + t * dy;
      
      return Math.sqrt(sqDist(point, [projX, projY]));
    };

    const simplifySegment = (start, end) => {
      if (end - start < 2) return [points[start]];

      let maxDist = 0;
      let maxIndex = start;

      for (let i = start + 1; i < end; i++) {
        const dist = perpendicularDist(points[i], points[start], points[end]);
        if (dist > maxDist) {
          maxDist = dist;
          maxIndex = i;
        }
      }

      if (maxDist > tolerance) {
        const left = simplifySegment(start, maxIndex);
        const right = simplifySegment(maxIndex, end);
        return [...left, ...right];
      } else {
        return [points[start]];
      }
    };

    const result = simplifySegment(0, points.length - 1);
    result.push(points[points.length - 1]);
    return result;
  }

  /**
   * Calculate path perimeter for adaptive tolerance
   */
  calculatePerimeter(points) {
    let perimeter = 0;
    for (let i = 0; i < points.length; i++) {
      const next = (i + 1) % points.length;
      const dx = points[next][0] - points[i][0];
      const dy = points[next][1] - points[i][1];
      perimeter += Math.sqrt(dx * dx + dy * dy);
    }
    return perimeter;
  }

  /**
   * Generate OpenSCAD file from points
   */
  generateSCAD(points, sourceName) {
    // Flip Y axis for OpenSCAD coordinate system
    const scadPoints = points.map(p => [p[0], -p[1]]);
    
    return `
// AUTOMATICALLY GENERATED BY SCOTT ENGINE (Node.js)
// Source: ${sourceName}
// Points: ${points.length}
$fn = 60;

// --- Configuration ---
Render_Mode = "Body"; // Options: "Body", "Lid"
Sign_Height = 30;
Wall_Thickness = 2;
Base_Thickness = 2;
Lid_Tolerance = 0.15;

// -- Engineering Constants --
CW = ("${this.lightType}" == "silicone_neon_6mm") ? 6.0 : 8.0; 
Lip_Overhang = 0.4;

module core_shape() {
    // Scott-Peucker Optimized Vector Path
    polygon(points=${JSON.stringify(scadPoints)});
}

module body_geometry() {
    difference() {
        linear_extrude(Sign_Height) offset(r = CW/2 + Wall_Thickness) core_shape();
        translate([0, 0, Base_Thickness]) linear_extrude(Sign_Height + 1) offset(r = CW/2) core_shape();
        
        // Friction Lip for Snap-Fit
        translate([0, 0, Sign_Height - 2.0]) linear_extrude(3.0)
            difference() {
                offset(r = CW/2 + 5) core_shape();
                offset(r = CW/2 - Lip_Overhang) core_shape();
            }
    }
}

module lid_geometry() {
    linear_extrude(2.0) offset(r = (CW/2 + 1.5) - Lid_Tolerance) core_shape();
}

if (Render_Mode == "Body") { body_geometry(); }
else { lid_geometry(); }
`;
  }

  /**
   * Process an image file and generate SCAD
   */
  async processImage(imagePath) {
    console.log(`\nProcessing: ${imagePath}`);
    
    // Load image and convert to grayscale
    const image = sharp(imagePath);
    const metadata = await image.metadata();
    console.log(`  Image size: ${metadata.width}x${metadata.height}`);

    // Convert to grayscale and threshold to binary
    const { data, info } = await image
      .grayscale()
      .raw()
      .toBuffer({ resolveWithObject: true });

    // Threshold to binary (white = shape, black = background)
    const threshold = 127;
    const binaryData = new Uint8Array(data.length);
    let whitePixels = 0;
    for (let i = 0; i < data.length; i++) {
      binaryData[i] = data[i] > threshold ? 255 : 0;
      if (binaryData[i] > 0) whitePixels++;
    }
    console.log(`  White pixels: ${whitePixels} (${(whitePixels / data.length * 100).toFixed(1)}%)`);

    // Trace boundary
    const boundary = this.traceBoundary(binaryData, info.width, info.height);
    console.log(`  Boundary points: ${boundary.length}`);

    if (boundary.length < 3) {
      return { success: false, error: 'No valid boundary detected' };
    }

    // Calculate adaptive tolerance based on perimeter
    const perimeter = this.calculatePerimeter(boundary);
    const adaptiveTolerance = this.tolerance * perimeter / 100;
    console.log(`  Perimeter: ${perimeter.toFixed(0)}px, Tolerance: ${adaptiveTolerance.toFixed(2)}px`);

    // Simplify using Douglas-Peucker
    const simplified = this.simplifyPath(boundary, adaptiveTolerance);
    console.log(`  Simplified: ${boundary.length} -> ${simplified.length} points`);

    // Generate SCAD
    const scadContent = this.generateSCAD(simplified, path.basename(imagePath));
    const outputPath = imagePath.replace(/\.[^.]+$/, '_scott.scad');
    fs.writeFileSync(outputPath, scadContent);
    console.log(`  Output: ${outputPath}`);

    return {
      success: true,
      input: imagePath,
      output: outputPath,
      originalPoints: boundary.length,
      simplifiedPoints: simplified.length,
      perimeter,
      samplePoints: simplified.slice(0, 5)
    };
  }
}

/**
 * Create a simple test image - a star shape
 */
async function createTestImage() {
  const size = 200;
  const center = size / 2;
  
  // Create SVG of a star
  const points = [];
  for (let i = 0; i < 5; i++) {
    // Outer point
    const outerAngle = (Math.PI / 2) + (i * 2 * Math.PI / 5);
    points.push(`${center + 70 * Math.cos(outerAngle)},${center - 70 * Math.sin(outerAngle)}`);
    // Inner point
    const innerAngle = outerAngle + Math.PI / 5;
    points.push(`${center + 30 * Math.cos(innerAngle)},${center - 30 * Math.sin(innerAngle)}`);
  }

  const svg = `<svg width="${size}" height="${size}" xmlns="http://www.w3.org/2000/svg">
    <rect width="100%" height="100%" fill="black"/>
    <polygon points="${points.join(' ')}" fill="white"/>
  </svg>`;

  const testPath = 'test_star.png';
  await sharp(Buffer.from(svg)).png().toFile(testPath);
  console.log(`Created test image: ${testPath}`);
  return testPath;
}

/**
 * Create a simple circle test
 */
async function createCircleTest() {
  const size = 200;
  const svg = `<svg width="${size}" height="${size}" xmlns="http://www.w3.org/2000/svg">
    <rect width="100%" height="100%" fill="black"/>
    <circle cx="100" cy="100" r="70" fill="white"/>
  </svg>`;

  const testPath = 'test_circle.png';
  await sharp(Buffer.from(svg)).png().toFile(testPath);
  console.log(`Created test image: ${testPath}`);
  return testPath;
}

/**
 * Create letter "A" test
 */
async function createLetterTest() {
  const size = 200;
  const svg = `<svg width="${size}" height="${size}" xmlns="http://www.w3.org/2000/svg">
    <rect width="100%" height="100%" fill="black"/>
    <text x="100" y="150" font-size="150" font-family="Arial" fill="white" text-anchor="middle">A</text>
  </svg>`;

  const testPath = 'test_letter_A.png';
  await sharp(Buffer.from(svg)).png().toFile(testPath);
  console.log(`Created test image: ${testPath}`);
  return testPath;
}

// Main test
async function runTests() {
  console.log('='.repeat(50));
  console.log('SCOTT ENGINE - NODE.JS ISOLATED TEST');
  console.log('='.repeat(50));

  const engine = new ScottSignEngine({ tolerance: 1.5 });

  // Test 1: Star shape
  console.log('\n--- Test 1: Star Shape ---');
  const starPath = await createTestImage();
  const starResult = await engine.processImage(starPath);
  console.log('Result:', JSON.stringify(starResult, null, 2));

  // Test 2: Circle
  console.log('\n--- Test 2: Circle ---');
  const circlePath = await createCircleTest();
  const circleResult = await engine.processImage(circlePath);
  console.log('Result:', JSON.stringify(circleResult, null, 2));

  // Test 3: Letter A
  console.log('\n--- Test 3: Letter A ---');
  const letterPath = await createLetterTest();
  const letterResult = await engine.processImage(letterPath);
  console.log('Result:', JSON.stringify(letterResult, null, 2));

  // Test 4: Tolerance comparison
  console.log('\n--- Test 4: Tolerance Comparison (Star) ---');
  for (const tol of [0.5, 1.0, 2.0, 5.0]) {
    const eng = new ScottSignEngine({ tolerance: tol });
    const result = await eng.processImage(starPath);
    console.log(`  Tolerance ${tol}: ${result.originalPoints} -> ${result.simplifiedPoints} points`);
  }

  // Show sample SCAD output
  console.log('\n--- Generated SCAD Preview (Star) ---');
  const scadContent = fs.readFileSync('test_star_scott.scad', 'utf-8');
  console.log(scadContent.split('\n').slice(0, 35).join('\n'));

  console.log('\n' + '='.repeat(50));
  console.log('TEST COMPLETE');
  console.log('Generated files: test_star_scott.scad, test_circle_scott.scad, test_letter_A_scott.scad');
  console.log('='.repeat(50));
}

runTests().catch(console.error);
