import cv2
import numpy as np
import os

class ScottSignEngine:
    def __init__(self, tolerance=2.0, light_type="silicone_neon_6mm"):
        self.tolerance = tolerance
        self.light_type = light_type
        self.scad_template = """
// AUTOMATICALLY GENERATED BY SCOTT ENGINE
// Source: {source_name}
$fn = 60;

// --- Configuration ---
Render_Mode = "Body"; // Options: "Body", "Lid"
Sign_Height = 30;
Wall_Thickness = 2;
Base_Thickness = 2;
Lid_Tolerance = 0.15;

// -- Engineering Constants (Scott Algorithm Derived) --
CW = ({light_type} == "silicone_neon_6mm") ? 6.0 : 8.0; 
Lip_Overhang = 0.4;

module core_shape() {{
    // Scott-Peucker Optimized Vector Path
    polygon(points={points});
}}

module body_geometry() {{
    difference() {{
        linear_extrude(Sign_Height) offset(r = CW/2 + Wall_Thickness) core_shape();
        translate([0, 0, Base_Thickness]) linear_extrude(Sign_Height + 1) offset(r = CW/2) core_shape();
        
        // Friction Lip for Snap-Fit
        translate([0, 0, Sign_Height - 2.0]) linear_extrude(3.0)
            difference() {{
                offset(r = CW/2 + 5) core_shape();
                offset(r = CW/2 - Lip_Overhang) core_shape();
            }}
    }}
}}

module lid_geometry() {{
    linear_extrude(2.0) offset(r = (CW/2 + 1.5) - Lid_Tolerance) core_shape();
}}

if (Render_Mode == "Body") {{ body_geometry(); }}
else {{ lid_geometry(); }}
"""

    def process_image(self, image_path):
        print(f"Processing: {image_path}")
        
        # 1. Load and Binarize
        img = cv2.imread(image_path, 0)
        if img is None:
            return f"Error: Could not load image {image_path}"
        
        print(f"  Image size: {img.shape}")
        _, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)
        
        # 2. Extract Contours (Moore-Neighbor Logic)
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        if not contours:
            return "No boundary detected."
        
        print(f"  Found {len(contours)} contours")

        # 3. Scott-Peucker Simplification
        main_contour = max(contours, key=cv2.contourArea)
        area = cv2.contourArea(main_contour)
        print(f"  Main contour area: {area:.0f} pixels")
        
        epsilon = self.tolerance * cv2.arcLength(main_contour, True) / 100.0
        approx_points = cv2.approxPolyDP(main_contour, epsilon, True)
        
        print(f"  Original points: {len(main_contour)}, Simplified: {len(approx_points)}")
        
        # Convert to list of [x, y] for OpenSCAD
        points_list = [[float(p[0][0]), float(-p[0][1])] for p in approx_points]

        # 4. Generate the SCAD File
        scad_output = self.scad_template.format(
            source_name=os.path.basename(image_path),
            light_type=f'"{self.light_type}"',
            points=points_list
        )
        
        output_name = os.path.splitext(image_path)[0] + "_scott.scad"
        with open(output_name, "w") as f:
            f.write(scad_output)
            
        print(f"  Output: {output_name}")
        print(f"  Points extracted: {len(points_list)}")
        
        # Return summary
        return {
            "success": True,
            "input": image_path,
            "output": output_name,
            "contours_found": len(contours),
            "original_points": len(main_contour),
            "simplified_points": len(approx_points),
            "area": area,
            "points": points_list[:5]  # First 5 points as sample
        }


def create_test_image():
    """Create a simple test image - a star shape"""
    img = np.zeros((200, 200), dtype=np.uint8)
    
    # Draw a simple star
    center = (100, 100)
    pts = []
    for i in range(5):
        # Outer point
        angle = np.radians(90 + i * 72)
        pts.append([int(center[0] + 60 * np.cos(angle)), int(center[1] - 60 * np.sin(angle))])
        # Inner point
        angle = np.radians(90 + i * 72 + 36)
        pts.append([int(center[0] + 25 * np.cos(angle)), int(center[1] - 25 * np.sin(angle))])
    
    pts = np.array([pts], dtype=np.int32)
    cv2.fillPoly(img, pts, 255)
    
    test_path = "test_star.png"
    cv2.imwrite(test_path, img)
    print(f"Created test image: {test_path}")
    return test_path


if __name__ == "__main__":
    print("=" * 50)
    print("SCOTT ENGINE - ISOLATED TEST")
    print("=" * 50)
    
    # Test 1: Create and process a simple star shape
    print("\n--- Test 1: Generated Star Shape ---")
    test_image = create_test_image()
    engine = ScottSignEngine(tolerance=1.5)
    result = engine.process_image(test_image)
    print(f"Result: {result}")
    
    # Test 2: Try different tolerance levels
    print("\n--- Test 2: Tolerance Comparison ---")
    for tol in [0.5, 1.0, 2.0, 5.0]:
        engine = ScottSignEngine(tolerance=tol)
        img = cv2.imread(test_image, 0)
        _, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        main = max(contours, key=cv2.contourArea)
        eps = tol * cv2.arcLength(main, True) / 100.0
        approx = cv2.approxPolyDP(main, eps, True)
        print(f"  Tolerance {tol}: {len(main)} -> {len(approx)} points")
    
    # Read and display the generated SCAD
    print("\n--- Generated SCAD Preview ---")
    with open("test_star_scott.scad", "r") as f:
        content = f.read()
        # Show first 40 lines
        lines = content.split('\n')[:40]
        for line in lines:
            print(line)
    
    print("\n" + "=" * 50)
    print("TEST COMPLETE - Check test_star_scott.scad")
    print("=" * 50)
