
// AUTOMATICALLY GENERATED BY SCOTT ENGINE (Node.js)
// Source: test_star.png
// Points: 11
$fn = 60;

// --- Configuration ---
Render_Mode = "Body"; // Options: "Body", "Lid"
Sign_Height = 30;
Wall_Thickness = 2;
Base_Thickness = 2;
Lid_Tolerance = 0.15;

// -- Engineering Constants --
CW = ("silicone_neon_6mm" == "silicone_neon_6mm") ? 6.0 : 8.0; 
Lip_Overhang = 0.4;

module core_shape() {
    // Scott-Peucker Optimized Vector Path
    polygon(points=[[99,-31],[118,-76],[165,-78],[128,-109],[140,-155],[100,-129],[59,-155],[71,-108],[34,-78],[81,-76],[99,-32]]);
}

module body_geometry() {
    difference() {
        linear_extrude(Sign_Height) offset(r = CW/2 + Wall_Thickness) core_shape();
        translate([0, 0, Base_Thickness]) linear_extrude(Sign_Height + 1) offset(r = CW/2) core_shape();
        
        // Friction Lip for Snap-Fit
        translate([0, 0, Sign_Height - 2.0]) linear_extrude(3.0)
            difference() {
                offset(r = CW/2 + 5) core_shape();
                offset(r = CW/2 - Lip_Overhang) core_shape();
            }
    }
}

module lid_geometry() {
    linear_extrude(2.0) offset(r = (CW/2 + 1.5) - Lid_Tolerance) core_shape();
}

if (Render_Mode == "Body") { body_geometry(); }
else { lid_geometry(); }
