// ==========================================================
// SIGNCRAFT 3D - OPENSCAD SOVEREIGN ENGINE GENERATOR
// Generates .scad files using Tri-Layer Metabolism System
// ==========================================================

export interface OpenSCADSettings {
  renderTarget: 'Body' | 'Lid' | 'Detail' | 'All';
  imageFile: string;
  fontSize: number;
  signHeight: number;
  channelWidth: number;
  lidTolerance: number;
  wireExitEnabled: boolean;
  mountingKeyholeEnabled: boolean;
}

export const defaultOpenSCADSettings: OpenSCADSettings = {
  renderTarget: 'All',
  imageFile: 'logo.svg',
  fontSize: 100,
  signHeight: 30,
  channelWidth: 6.0,
  lidTolerance: 0.18,
  wireExitEnabled: true,
  mountingKeyholeEnabled: true
};

export function generateOpenSCADFile(settings: OpenSCADSettings): string {
  const {
    renderTarget,
    imageFile,
    fontSize,
    signHeight,
    channelWidth,
    lidTolerance,
    wireExitEnabled,
    mountingKeyholeEnabled
  } = settings;

  const scadCode = `// ==========================================================
// SIGNCRAFT 3D - SOVEREIGN ENGINE V16
// Generated by SignCraft 3D Web Application
// Logic: Tri-Layer Metabolism for Multi-Material Signs
// ==========================================================

/* [Export Options] */
Render_Target = "${renderTarget}"; // [Body, Lid, Detail, All]

/* [Engineering Constants] */
Image_File = "${imageFile}"; 
Font_Size = ${fontSize};
Sign_Height = ${signHeight};
CW = ${channelWidth}; // Neon Channel Width (mm)
Lid_Tolerance = ${lidTolerance}; 

/* [Features] */
Wire_Exit = ${wireExitEnabled ? 'true' : 'false'};
Mounting_Keyhole = ${mountingKeyholeEnabled ? 'true' : 'false'};

// ==========================================================
// SOURCE GEOMETRY MODULE
// ==========================================================
module source_geometry() {
    scale([0.1, 0.1, 1] * Font_Size) import(Image_File, center=true);
}

// ==========================================================
// BODY: The Chassis (Red or Black PLA+)
// Outer shell with LED channel cavity
// ==========================================================
module render_body() {
    difference() {
        // Outer shell with offset
        linear_extrude(Sign_Height) 
            offset(r = CW/2 + 2.5) 
                source_geometry();
        
        // Inner LED channel cavity
        translate([0, 0, 2.5]) 
            linear_extrude(Sign_Height) 
                offset(r = CW/2) 
                    source_geometry();
        
        // Wire Exit Hole
        ${wireExitEnabled ? `translate([0, -Font_Size/2, 6]) 
            rotate([90, 0, 0]) 
                cylinder(h=20, r=3, $fn=20);` : '// Wire exit disabled'}
        
        // Mounting Keyhole (optional)
        ${mountingKeyholeEnabled ? `translate([0, Font_Size/2, Sign_Height/2]) 
            rotate([-90, 0, 0]) {
                cylinder(h=10, r=4, $fn=20);
                translate([0, 0, 5]) cylinder(h=5, r=2, $fn=20);
            }` : '// Mounting keyhole disabled'}
    }
}

// ==========================================================
// LID: The Diffuser (Translucent White PLA)
// Snap-fit cover for LED channel
// ==========================================================
module render_lid() {
    linear_extrude(2.0) 
        offset(r = (CW/2 + 1.5) - Lid_Tolerance) 
            source_geometry();
}

// ==========================================================
// DETAIL: The Detail Overlay (Black Carbon Fiber/Conductive PLA)
// Captures the 'Pilot' lines that generic converters lose
// ==========================================================
module render_detail() {
    linear_extrude(1.2) 
        source_geometry();
}

// ==========================================================
// SOVEREIGN LAYER ENGINE - RENDER DISPATCHER
// ==========================================================
if (Render_Target == "Body") {
    render_body();
} else if (Render_Target == "Lid") {
    render_lid();
} else if (Render_Target == "Detail") {
    render_detail();
} else if (Render_Target == "All") {
    // Preview all layers with color coding and spacing
    color("red", 0.8) render_body();
    color("white", 0.6) translate([0, 0, Sign_Height + 5]) render_lid();
    color("black", 0.9) translate([0, 0, Sign_Height + 10]) render_detail();
}

// ==========================================================
// MANUFACTURING NOTES
// ==========================================================
// Body:   Print in PLA+ (Red or Black) - Main structural piece
// Lid:    Print in Translucent White PLA - LED diffuser
// Detail: Print in Black PLA or Carbon Fiber - Fine line overlay
//
// Assembly:
// 1. Insert LED strip into Body channel
// 2. Route wires through wire exit hole
// 3. Press-fit Lid into channel (friction fit with tolerance)
// 4. Align Detail overlay on top for fine line registration
// ==========================================================
`;

  return scadCode;
}

// Generate separate files for each layer
export function generateOpenSCADLayerFiles(settings: OpenSCADSettings): {
  body: string;
  lid: string;
  detail: string;
} {
  return {
    body: generateOpenSCADFile({ ...settings, renderTarget: 'Body' }),
    lid: generateOpenSCADFile({ ...settings, renderTarget: 'Lid' }),
    detail: generateOpenSCADFile({ ...settings, renderTarget: 'Detail' })
  };
}
